name: CI
on: pull_request
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test -- run

      - name: Build
        run: npm run build