name: CI (Test and Build)
on:
  pull_request:
    paths:
      - './ui/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: ./ui/.nvmrc

      - name: Install Dependencies
        run: npm install
        working-directory: ./ui

      - name: Lint
        run: npm run lint
        working-directory: ./ui

      - name: Prettier
        run: npm run prettier
        working-directory: ./ui

      - name: Tests
        run: npm run test -- run
        working-directory: ./ui

      - name: Build
        run: npm run build
        working-directory: ./ui
